
module(array Modules/arraymodule.c)
module(math Modules/mathmodule.c)
module(cmath Modules/cmathmodule.c)
module(time Modules/timemodule.c)
module(datetime Modules/datetimemodule.c REQUIRES time)
module(binascii Modules/binascii.c)
module(itertools Modules/itertoolsmodule.c)
module(future_builtins Modules/future_builtins.c REQUIRES itertools)
module(strop Modules/stropmodule.c)
module(cStringIO Modules/cStringIO.c)
module(cPickle Modules/cPickle.c REQUIRES cStringIO)
module(parser Modules/parsermodule.c)
module(unicodedata Modules/unicodedata.c)
module(select Modules/selectmodule.c)
module(xxsubtype Modules/xxsubtype.c)
module(imageop Modules/imageop.c)

if(Z_PYTHON_WITH_THREADS)
    module(thread Modules/threadmodule.c)
elseif(Z_PYTHON_MODULE_thread)
    message(STATUS "WARNING: not building the \"thread\" module (Z_PYTHON_WITH_THREADS is OFF).")
endif()

if(WIN32)
    module(msvcrt PC/msvcrtmodule.c)
else()
    module(mmap Modules/mmapmodule.c)
    module(fcntl Modules/fcntlmodule.c)
endif()
