
set(objects_files
    Objects/stringlib/count.h
    Objects/stringlib/ctype.h
    Objects/stringlib/fastsearch.h
    Objects/stringlib/find.h
    Objects/stringlib/formatter.h
    Objects/stringlib/localeutil.h
    Objects/stringlib/partition.h
    Objects/stringlib/split.h
    Objects/stringlib/string_format.h
    Objects/stringlib/stringdefs.h
    Objects/stringlib/transmogrify.h
    Objects/stringlib/unicodedefs.h
    Objects/abstract.c
    Objects/boolobject.c
    Objects/bufferobject.c
    Objects/bytearrayobject.c
    Objects/bytes_methods.c
    Objects/capsule.c
    Objects/cellobject.c
    Objects/classobject.c
    Objects/cobject.c
    Objects/codeobject.c
    Objects/complexobject.c
    Objects/descrobject.c
    Objects/dictobject.c
    Objects/enumobject.c
    Objects/exceptions.c
    Objects/fileobject.c
    Objects/floatobject.c
    Objects/frameobject.c
    Objects/funcobject.c
    Objects/genobject.c
    Objects/intobject.c
    Objects/iterobject.c
    Objects/listobject.c
    Objects/longobject.c
    Objects/memoryobject.c
    Objects/methodobject.c
    Objects/moduleobject.c
    Objects/object.c
    Objects/obmalloc.c
    Objects/rangeobject.c
    Objects/setobject.c
    Objects/sliceobject.c
    Objects/stringobject.c
    Objects/structseq.c
    Objects/tupleobject.c
    Objects/typeobject.c
    Objects/unicodectype.c
    Objects/unicodeobject.c
    Objects/unicodetype_db.h
    Objects/weakrefobject.c
)

source_group("Source Files\\Objects" FILES ${objects_files})
